kind: Deployment
apiVersion: apps/v1
metadata: 
 name: nginx-hello-world
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx-hello-world
 revisionHistoryLimit: 5
 progressDeadlineSeconds: 300
 minReadySeconds: 10
 strategy:
  type: RollingUpdate
  rollingUpdate: 
   maxUnavailable: 1
   maxSurge: 1
 template:
  metadata:
    labels:
     app: nginx-hello-world
  spec:
    containers:
    -  name: nginx-hello-world-ctr
       image: __IMAGE__@__DIGEST__
       ports:
       - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
 name: nginx-hello-world-svc
 labels:
  app: nginx-hello-world
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 30003
   protocol: TCP
 selector:
  app: nginx-hello-world